### ISSUE TITLE
Question about RaMP database installing

### ISSUE THREAD

**Issue by fuyaloha** [ncats/RaMP-DB#21]
I am trying to install RaMP database according to the instruction. I am not familiar with mysql language, but it looks like it does not work. 
Could you please help me out?  Below is my screenshot in R. Many thanks for your help.
> mysql -u root -p ramp < myramp.sql
Error: unexpected symbol in "mysql -u root"

Thanks,
Yuanyuan

**Comment by fuyaloha** [comment]
I also tried in MySQL, but still got Error below: 
mysql> mysql -u root -p ramp < /YFu/download/RaMP_databasde/RaMP-DB-master/inst/extdata/ramp180302.sql
    -> use ramp;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysql -u root -p ramp < /YFu/download/RaMP_database/RaMP-DB-maste' at line 1

Could you please help? My email : fuy@hawaii.edu

Thank you very much,
Yuanyuan

**Comment by johnbraisted** [comment]
Hi @fuyaloha Yuanyuan,

One mysql command set is used to enter the mysql command line and build an empty ramp database, without tables and without data. The second command loads the .sql file to construct the structure of the database and populate the data. It looks to me that you are on the mysql command line and while still in mysql you are trying to do the load. The load command should be run after you 'exit' mysql.

On the command line run these commands shown just below. The first command just opens up mysql and gets you on the mysql command line. The second command, after you are in mysql, 'create database ramp;' will create the database. Then 'exit;' will get you back to the command line (outside of the mysql command line tool). It's important to make sure that you exit mysql because the next command in the instruction is designed to be run outside of mysql, not inside the mysql 'client' command line tool.

**mysql -u root -p
mysql> create database ramp;
mysql> exit;**

After these command, you should have created the empty ramp database and you should be out of the mysql 'client' (mysql command line tool).

This command below should be run on the command line. Note that from your comment that it appears that you were running this command from within mysql. If you have exited mysql with the 'exit' command above, the command below will work for you. You will want to provide the complete path and file name to your ramp180302.sql file. 

**mysql -u root -p ramp < _/put-your-full-path-to-the-file-here/ramp180302.sql_**

This should work. Thanks for your interest in RaMP.

Best,
John
