### ISSUE TITLE
SQL Call issue only_full_group_by

### ISSUE THREAD

**Issue by Mathelab** [ncats/RaMP-DB#26]
Running into a MySQL issue when calling any RaMP functions that connect with the ramp MySQL database:

```
> fisher.results <- runCombinedFisherTest(analytes = c("hmdb:HMDB0000033","hmdb:HMDB0000052"))
[1] "Running Fisher's tests on metabolites"
[1] "Fisher Testing ......"
[1] "Starting getPathwayFromAnalyte()"
[1] "Working on ID List..."
Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ramp2.p.pathwayName' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [1055]
```

The issue is due to the "ONLY_FULL_GROUP_BY" which is introduced in some MySQL versions.

**Comment by johnbraisted** [comment]
The issue was specifically in the runCombinedFisherTest and getPathwaysFromAnalyte. The SQL method in getPathwaysFromAnalyte had syntax that was not compatible, by default, with MySQL version 5.7.34 and later versions. This issue was only within the development version of RaMP (dev) branch. The issue has been resolved by altering the sql syntax to be compatible with the default settings in newer versions of MySQL.
