### ISSUE TITLE
warnings in findCluster under R 4.2

### ISSUE THREAD

**Issue by nlichti** [ncats/RaMP-DB#37]
Hi. Running the vignette, findCluster gives warnings related to the && in line 107 of the function definition under R 4.2.0.  This will become an error at some point in the future.  See "Changes to logical functions" at https://www.r-bloggers.com/2022/04/new-features-in-r-4-2-0/.    

It's great to be able to access all of these resources in one place with a clean, programmable interface. Looking forward to using it.

**Comment by johnbraisted** [comment]
Hi.  Thanks very much for sending word on this. It looks like the && in this case is applied operands that are vectors rather than scalar values, like single boolean values. We'll need to dig into this to put in a patch. I really appreciate the notification and the link to r-bloggers. It's very helpful. Thanks. We'll put this on our list to patch.
