### ISSUE TITLE
Error installing RaMP locally with R

### ISSUE THREAD

**Issue by KristinaGagalova** [ncats/RaMP-DB#40]
Hi, 
I am using a Windows laptop + Rstudio and I am having the following error when installing RaMP as a remote db. 
Could you please take a look?
```
remotes::install_github("Mathelab/RaMP-DB")
....
── R CMD build ───────────────────────────────────────────────────────────────
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.2 from https://cran.r-project.org/bin/windows/Rtools/ or https://www.r-project.org/nosvn/winutf8/ucrt3/.
✔  checking for file 'C:\Users\krist\AppData\Local\Temp\Rtmpy6pOjk\remotes2cf01a0a77eb\Mathelab-RaMP-DB-5acaded/DESCRIPTION' ...
─  preparing 'RaMP':
✔  checking DESCRIPTION meta-information ... 
   Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
     PCRE pattern compilation error
   	'unrecognized character follows \'
   	at 'img/.*$'
   Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
     invalid regular expression '^\img/.*$'
   Execution halted
Error: Failed to install 'RaMP' from GitHub:
  ! System command 'Rcmd.exe' failed
```
I am not sure if that's related to ```Rtools``` that cannot be detected. 
Thank you in advance
Kristina

**Comment by KristinaGagalova** [comment]
FYI - I just installed Rtools and I still see the same error
```
── R CMD build ───────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\krist\AppData\Local\Temp\RtmpKmbshU\remotes12b02768608e\Mathelab-RaMP-DB-5acaded/DESCRIPTION' ...
─  preparing 'RaMP': (353ms)
✔  checking DESCRIPTION meta-information ... 
   Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
     PCRE pattern compilation error
   	'unrecognized character follows \'
   	at 'img/.*$'
   Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
     invalid regular expression '^\img/.*$'
   Execution halted
Error: Failed to install 'RaMP' from GitHub:
  ! System command 'Rcmd.exe' failed
```

**Comment by johnbraisted** [comment]
Hi Kristina,

Apologies for the delayed response. Your path for the installation is to Dr. Mathé’s old github project from the project’s early days at The Ohio State University.
Please refer to the ncats github project during installation:

https://github.com/ncats/RaMP-DB

There are full instructions on the page and they include a link to download the database version that corresponds to the package build.
Below is copied from the page. We suggest using the devtools package install_github method, but other options may work as long as you point to the proper github repository.

# Locally install RaMP
install.packages("devtools")
library(devtools)
install_github("ncats/RAMP-DB")

Best,
John


John C. Braisted [C]
Informatics Scientist
National Center for Advancing Translational Sciences
9800 Medical Center Drive
Rockville, MD 20850

[National Center for Advancing Translational Sciences: Collaborate Innovate Accelerate]




From: Kristina Gagalova ***@***.***>
Sent: Tuesday, December 20, 2022 8:28 PM
To: ncats/RaMP-DB ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [ncats/RaMP-DB] Error installing RaMP locally with R (Issue #40)


Hi,
I am using a Windows laptop + Rstudio and I am having the following error when installing RaMP as a remote db.
Could you please take a look?

remotes::install_github("Mathelab/RaMP-DB")



....



── R CMD build ───────────────────────────────────────────────────────────────



WARNING: Rtools is required to build R packages, but is not currently installed.







Please download and install Rtools 4.2 from https://cran.r-project.org/bin/windows/Rtools/ or https://www.r-project.org/nosvn/winutf8/ucrt3/.



✔  checking for file 'C:\Users\krist\AppData\Local\Temp\Rtmpy6pOjk\remotes2cf01a0a77eb\Mathelab-RaMP-DB-5acaded/DESCRIPTION' ...



─  preparing 'RaMP':



✔  checking DESCRIPTION meta-information ...



   Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :



     PCRE pattern compilation error



        'unrecognized character follows \'



        at 'img/.*$'



   Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) :



     invalid regular expression '^\img/.*$'



   Execution halted



Error: Failed to install 'RaMP' from GitHub:



  ! System command 'Rcmd.exe' failed



I am not sure if that's related to Rtools that cannot be detected.
Thank you in advance
Kristina

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fncats%2FRaMP-DB%2Fissues%2F40&data=05%7C01%7Cjohn.braisted%40nih.gov%7Cd0611db90bd64660523208dae2f2a9bf%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638071829109434559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MQytJkkghNkx3JU4upz5dB%2BUXpCZ1lSXbzy%2BjCWeazU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANSEECV5TXPHVRRCRB4AR3WOJMLVANCNFSM6AAAAAATFDCMJQ&data=05%7C01%7Cjohn.braisted%40nih.gov%7Cd0611db90bd64660523208dae2f2a9bf%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638071829109434559%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=u2I%2FqihAUDLDiENmSD1FIe6fQfVD3uuOTfCosh5Yphs%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by KristinaGagalova** [comment]
That worked better, indeed! Thank you for the suggestion
