### ISSUE TITLE
Biological pathway enrichment only include metabolites

### ISSUE THREAD

**Issue by AScamila** [ncats/RaMP-DB#41]
I'm using the web tool for  biological pathway enrichment analysis using inputs from genes, proteins, metabolites and lipids. However,  the analytes included in the enriched pathways only include metabolites and lipids. 
Is there a bug in the code that only consider metabolites and lipids for the analysis ?

**Comment by johnbraisted** [comment]
Hi, I'm very sorry for the delay in response. Genes or proteins would be best identified using uniprot accessions or HGNC official gene symbols, or NCBI gene id (entrez). RaMP requires that ids are 'prefixed', in this case the prefix would be 'uniprot:' or 'gene_symbol:', or 'entrez:' as appropriate for your data. Note that most data comes from sources that focus on human proteins and since we feature mostly metabolic pathways, enzymes tend to have more coverage, along with some transporters and signalling proteins. The database version we are about to put out in the next few days has 57250 distinct uniprot ids, that map to 14534 distinct proteins (some are secondary uniprot accessions). If 13216 of those distinct proteins map to at least 1 pathway in RaMP. I'm just providing some idea about our coverage. Please feel free to share some ids and I'll be happy to determine where we missed them. Best, John Braisted, RaMP Developer

**Comment by johnbraisted** [comment]
Hi Camila,

Sorry if this is a repeat message. I responded on the GitHub Issue tracker. I'll paste it in an email to you.

==

I'm very sorry for the delay in response. Genes or proteins would be best identified using uniprot accessions or HGNC official gene symbols, or NCBI gene id (entrez). RaMP requires that ids are 'prefixed', in this case the prefix would be 'uniprot:' or 'gene_symbol:', or 'entrez:' as appropriate for your data. Note that most data comes from sources that focus on human proteins and since we feature mostly metabolic pathways, enzymes tend to have more coverage, along with some transporters and signalling proteins. The database version we are about to put out in the next few days has 57250 distinct uniprot ids, that map to 14534 distinct proteins (some are secondary uniprot accessions). If 13216 of those distinct proteins map to at least 1 pathway in RaMP. I'm just providing some idea about our coverage. Please feel free to share some ids and I'll be happy to determine where we missed them.

Best,

John

John C. Braisted [C]
Informatics Scientist
National Center for Advancing Translational Sciences
9800 Medical Center Drive
Rockville, MD 20850

[National Center for Advancing Translational Sciences: Collaborate Innovate Accelerate]






From: Camila Alvarez-Silva ***@***.***>
Sent: Thursday, January 12, 2023 5:55 AM
To: ncats/RaMP-DB ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [ncats/RaMP-DB] Biological pathway enrichment only include metabolites (Issue #41)


I'm using the web tool for biological pathway enrichment analysis using inputs from genes, proteins, metabolites and lipids. However, the analytes included in the enriched pathways only include metabolites and lipids.
Is there a bug in the code that only consider metabolites and lipids for the analysis ?

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fncats%2FRaMP-DB%2Fissues%2F41&data=05%7C01%7Cjohn.braisted%40nih.gov%7C8b3edc1e2f9442555e6c08daf48b702c%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638091176965443095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RnGa%2FPbeTI8yl8xj2Xy9peV9rvQve3ML3fzXTXeINKM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANSEEH2BGTCHITLJJQJ7KLWR7PH3ANCNFSM6AAAAAATZDLSCA&data=05%7C01%7Cjohn.braisted%40nih.gov%7C8b3edc1e2f9442555e6c08daf48b702c%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638091176965443095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TcSxFzMHmn%2FqKkN5JYPM4dN3CqljqraiCpNFAqbKiKc%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by AScamila** [comment]
Hi Johan,
Thank you for your answer! Do you have a day for the release of the new database?
Best,
Camila

From: johnbraisted ***@***.***>
Reply to: ncats/RaMP-DB ***@***.***>
Date: Monday, 30 January 2023 at 22.12
To: ncats/RaMP-DB ***@***.***>
Cc: Maria Camila Alvarez Silva ***@***.***>, Author ***@***.***>
Subject: Re: [ncats/RaMP-DB] Biological pathway enrichment only include metabolites (Issue #41)


You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi Camila,

Sorry if this is a repeat message. I responded on the GitHub Issue tracker. I'll paste it in an email to you.

==

I'm very sorry for the delay in response. Genes or proteins would be best identified using uniprot accessions or HGNC official gene symbols, or NCBI gene id (entrez). RaMP requires that ids are 'prefixed', in this case the prefix would be 'uniprot:' or 'gene_symbol:', or 'entrez:' as appropriate for your data. Note that most data comes from sources that focus on human proteins and since we feature mostly metabolic pathways, enzymes tend to have more coverage, along with some transporters and signalling proteins. The database version we are about to put out in the next few days has 57250 distinct uniprot ids, that map to 14534 distinct proteins (some are secondary uniprot accessions). If 13216 of those distinct proteins map to at least 1 pathway in RaMP. I'm just providing some idea about our coverage. Please feel free to share some ids and I'll be happy to determine where we missed them.

Best,

John

John C. Braisted [C]
Informatics Scientist
National Center for Advancing Translational Sciences
9800 Medical Center Drive
Rockville, MD 20850

[National Center for Advancing Translational Sciences: Collaborate Innovate Accelerate]






From: Camila Alvarez-Silva ***@***.***>
Sent: Thursday, January 12, 2023 5:55 AM
To: ncats/RaMP-DB ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [ncats/RaMP-DB] Biological pathway enrichment only include metabolites (Issue #41)


I'm using the web tool for biological pathway enrichment analysis using inputs from genes, proteins, metabolites and lipids. However, the analytes included in the enriched pathways only include metabolites and lipids.
Is there a bug in the code that only consider metabolites and lipids for the analysis ?

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fncats%2FRaMP-DB%2Fissues%2F41&data=05%7C01%7Cjohn.braisted%40nih.gov%7C8b3edc1e2f9442555e6c08daf48b702c%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638091176965443095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RnGa%2FPbeTI8yl8xj2Xy9peV9rvQve3ML3fzXTXeINKM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANSEEH2BGTCHITLJJQJ7KLWR7PH3ANCNFSM6AAAAAATZDLSCA&data=05%7C01%7Cjohn.braisted%40nih.gov%7C8b3edc1e2f9442555e6c08daf48b702c%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638091176965443095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TcSxFzMHmn%2FqKkN5JYPM4dN3CqljqraiCpNFAqbKiKc%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
