### ISSUE TITLE
RAMP not recognizing known HMDBs

### ISSUE THREAD

**Issue by Y11** [ncats/RaMP-DB#54]
Hello,

I recently input a list of HMDBs into both "Chemical Classes from Metabolites" and "Biological Pathway Enrichment" into the GUI version and was surprised to see how many metabolites were not recognized, even though they seem to be present in HMDB 5.0, dating back to before the date you have listed on the Source Data section.  Any help/explanation you can provide for this?
 Examples:  "There were no matches for the following pathways: hmdb:hmdb00532, hmdb:hmdb00821, hmdb:hmdb32055, hmdb:hmdb62551, hmdb:hmdb61115, hmdb:hmdb04983"
Thanks!

**Comment by tsheils** [comment]
It appears as though our search is case-sensitive - these values with HMDB in uppercase after the colon return results hmdb:HMDB00532, hmdb:HMDB00821, hmdb:HMDB32055, hmdb:HMDB62551, hmdb:HMDB61115, hmdb:HMDB04983, with the exception of hmdb:HMDB62551

**Comment by tsheils** [comment]
@Y11 it may be a little more complicate in that - my example was using the rampdb.nih.gov UI. Another developer will provide some updates soon.

**Comment by johnbraisted** [comment]
Hi Y11,

I looked into this a bit closer. The query from the UI is case sensitive. 

There is one other issue. These IDs are an older format of HMDB ids. For version 5.0 (and perhaps 4.0) they extended the length of their IDs by adding to zeros just after HMDB. These that I share here will work. Note that I've just added the two zeros. The original ids are secondary IDs. We do map those to pathways, but our current database doesn't map secondary ids to chemical classes. I think we can enable that in future versions. The best thing to do is to verify the length of the IDs. Some metabolomics cores and companies/vendors have older annotations on some of their results. Sorry for the inconvenience.

hmdb:hmdb0000532, hmdb:hmdb0000821, hmdb:HMDB0032055, hmdb:HMDB0062551, hmdb:HMDB0061115 hmdb:HMDB0004983

So, the chemical class survey didn't return for these because of the format. The pathway result is a bit different. The pathway enrichment option, and the simple query for pathways from analytes will take older HMDB IDs that are shorter (secondary IDs). The issue for these particular metabolites is that none of the map to a RaMP pathway (from Reactome, WikiPathways, and the portion of KEGG that we capture). I see the IDs in our main source table that lists all source ids, but the number of pathways listed for these ids is 0 for each one. 

Thanks for using RaMP. Please let us know if you have any other questions.


Note that here I have all of the actual IDs as upper case.

**Comment by Y11** [comment]
Thanks - this is so incredibly helpful!!  I'll ping back if any questions come up when I update my code.
Y

**Comment by johnbraisted** [comment]
Resolved. Closing this issue.
