### ISSUE TITLE
RAMP cIDs mapped to structurally different chemicals?

### ISSUE THREAD

**Issue by anna-s-young** [ncats/RaMP-DB#74]
Hello,

I noticed that certain ramp compound IDs are mapped to multiple, structurally unique chemicals in the sql tables. For example, in the "chem_props" table, RAMP_C_000000001 is mapped to two different InChiKeys, for both 1-methylhistidine and 3-methylhistidine. So, while most linked IDs of other sources are equivalent or synonyms, they aren't all (e.g., in the "source" table). It seems that there are ~28K ramp cIDs with more than one unique InChiKey mapped to it. Is this an error, or am I misunderstanding something? 

Thanks in advance for clarifying, and for this great resource,
Anna

**Comment by johnbraisted** [comment]
Hi Anna,

We started creating RaMP ids very early on in RaMP because we pull in multiple resources and each resource might have its own id type (like HMDB and ChEBI) and also have multiple cross references to other ids. The RaMP IDs are a way to harmonize metabolites from multiple resources but were primarily created to ease mapping to metabolic pathways from our data sources. In most cases, especially for polar compounds, a ramp id will map to a specific compound, but in some cases, especially lipids where a pathway may not specify a specific structure (like specifying a generic fatty acid), we use this fuzzy matching to help get user's ids to map to pathways. 

Under the hood, we take in our resources' metabolite id and all cross-references to other id types. If we encounter the cross referenced id from another source, those metabolites are merged under a common ramp-id. In this specific case, HMDB0000001 (1-methylhistidine) and HMDB00000479 (3-methylhistidine) both have a cross-reference in HMDB to KEGG's C01152. So these end up being connected under one RaMP ID. *Note this is primarily for mapping to pathways.

Also in the backend, we do one simple check to make sure that any two merged metabolite (under one ramp id) have less than a 10% difference in mass, from the smaller of the two metabolites. This helps to capture mappings that are just completely wrong. We manually curate that set of clearly wrong mismatches and if it's really a problem, then the pair of ids go on an exclusion list so we can ignore the cross reference and keep them separate.

Finally, occasionally we will have two data sources that feature exactly the same compound, but no resources cross-reference the other. For those we look for common inchi-key (minus the last letter, protonation state, I believe) and merge under one ramp id. One example has been Arachidonic Acid from HMDB and Arachidonate from ChEBI. The inchi-key caught this and merged them under one ramp id. 

Note that although the chem_props table includes a ramp id, our web interface and RaMP R package only uses the column labeled chem_source_id. Queries on chemical properties do not map through our 'source' table from source id to ramp id. For chemical properties, we want to deliver a specific structure specified by our data sources. For our chemical properties table, the data sources are HMDB, ChEBI and LIPIDMAPS. 

Thanks for your interest in RaMP. We realize that the ramp-id concept can be confusing, but it's primarily for mapping to pathways. 

One last note our figshare project area has a new mysql dump v2.5.4 updated this month.  
https://figshare.com/account/home#/projects/137373

Also, our package is not being built around using sqlite rather than mysql. We have sqlite versions of the files in git-hub large file storage, here:
https://github.com/ncats/RaMP-DB/tree/sqlite/db

Right now the package and the sqlite data dumps are in our 'sqlite' branch at github, but we'll release this as our main release very soon. 

Best,
John Braisted
NCATS RaMP Team

**Comment by anna-s-young** [comment]
Hi John,

Thank you very much for taking the time to clarify this! That makes sense now. And thank you for sharing the updated files.

Appreciate your help!
Anna

**Comment by anna-s-young** [comment]
Hi John,

Thanks again for your guidance. I have a follow-up question about the sql data dumps, if you don't mind clarifying:

Some of the RAMP compound IDs map to distinct molecular weights (and monoisotopic masses) that are different by more than 10%, which I thought was the threshold used to flag mismappings for manual curation. Does this mean that they were indeed manually checked but still deemed to be the same compound for the purposes of pathway analysis? As an example, RAMP_C_000002272 in the chem_props table of the latest mysql data dump that you pointed me towards (v2.5.4_20240411) is shown in the attached screenshot with MW ranging from 481 to 678. An example in the previous mysql data dump (v2.3.0_20230727) is RAMP_C_000235687, with MWs as different as 920 and 752, and I don't see those listed in the curation_mapping_issues_list file.

I also noticed that the RAMP compound IDs aren't always the same across mysql data dump versions - is that to be expected? (I assume so since these IDs don't need to be handled by the user in the R package). For example, quinolinic acid is RAMP_C_000218369 in v2.3.0 but RAMP_C_000000784 in v2.5.4, and RAMP_C_000218369 in v2.5.4 refers to something else.

Thank you again!!
Anna

v2.5.4 example:

![different MWs in v2 5 4](https://github.com/ncats/RaMP-DB/assets/164892851/3cf183c6-0095-4f5d-895a-cafd7a63cbcf)

v2.3.0 example:
![diff MWs in v2 3 0](https://github.com/ncats/RaMP-DB/assets/164892851/1ffc9b30-ca8a-4729-8c19-a3300980fd55)

**Comment by KeithKelleher** [comment]
Thank you for the bug report and the followup. You pointed out some problems which required fixes to the database builder in how entities are merged.

The database updates are not released yet, but a fixed version is available here: https://github.com/ncats/RaMP-DB/blob/ramp3.0/db/RaMP_SQLite_v2.6.3.sqlite.gz

Feel free to download it. If you want to use it with the R package, it's possible to do before release.
* Find where your database files are cached when loading to the RaMP R Package
  * Run this at the R prompt `BiocFileCache:::getBFCOption("CACHE")`
* download the unreleased version to that folder
* load your database like this:
  * `rampDB = RaMP(version="2.6.3")`

Let me know if there are any more issues.
